### ISSUE TITLE
str.indexOf is not a function

### ISSUE THREAD

**Issue by xplorld** [boginw/js-y86-64#5]
y64 code:
```
# Execution begins at address 0
    .pos 0
    irmovq stack, %rsp      # Set up stack pointer
    call main       # Execute main program
    halt            # Terminate program

f0:
        irmovq $0x10, %rax
        ret
f1:
        irmovq $0x11, %rax
        ret
f2:
        irmovq $0x12, %rax
        ret
f3:
        irmovq $0x13, %rax
        ret
f4:
        irmovq $0x14, %rax
        ret

jtable:
    .quad f0
    .quad f1
    .quad f2
    .quad f3
    .quad f4

jmp_to_n:
    pushq %rdi
    mrmovq -3(%rsp), %rbx # rbx = 8 * rdi
    mrmovq jtable(%rbx), %rbx
    irmovq 2, %r10
    rmmovq %rbx, real_jmp(%r10) # *real_jmp = %rbx
real_jmp:
    jmp jtable
    
main:
    irmovq $0x2,%rdi
    call jmp_to_n
    ret

# Stack starts here and grows to lower addresses
    .pos 0x200
stack:

```

behavior:
![image](https://user-images.githubusercontent.com/7023694/46635515-a056fe00-cb09-11e8-975c-410f1deec000.png)

**Comment by boginw** [comment]
It's been a while since I worked on this project. But as far as I remember, `mrmovq D(rB), rA` does not support `D` being a label. I would like to keep the project close to the language described in [Computer Systems, A Programmer's Perpective, Third Edition](https://www.amazon.com/gp/offer-listing/1292101768/?tag=wwwcampusboocom587-20&condition=new). 

I'd be happy to implement this for you, but I will some example, that this is actually supported by the langauge.

**NB**: The error occurs [here](https://github.com/boginw/js-y86-64/blob/master/js/general.js#L186)

**Comment by boginw** [comment]
As no further development has been made in 2 months, I'm closing this issue.
